### PR TITLE
Update member list

### PR DESCRIPTION
**Pull request by amatas**

### CODE REVIEW

**Comment by waharnum** [comment]
LGTM.

**Comment by stegru** [comment]
How come @gtirloni is getting chopped off?

**Comment by waharnum** [comment]
@stegru Gio has moved on from the IDRC to a new opportunity (we wish him the best!). I've been working with him on transition and since this is his first week on the new job, we're offboarding his accounts etc from various places.

**Comment by mrtyler** [comment]
LGTM

**Pull request merged**
