### PR TITLE
NOJIRA - Add lint checks to Linux-based jobs

### PR DESCRIPTION
**Pull request by gtirloni**
Also renamed some tasks so they're grouped together in Jenkins.

### CODE REVIEW

**Comment by gtirloni** [comment]
@GPII/core-architecture-committers any concerns with having `grunt lint` be a mandatory verification in CI?

**Comment by cindyli** [comment]
+1 on adding the linting step.

**Comment by simonbates** [comment]
+1 on including lint check from me also

**Comment by gtirloni** [comment]
Thanks. If this causes any undesired effects I can work on fixing them ASAP.

**Pull request merged**
