### PR TITLE
NOJIRA: Remove gpii-X projects being migrated from Jenkins CI.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
In preparation for setting up GitHub Actions, this PR will get rid of the migrating repositories' CI jobs on Jenkins.

cc: @amb26

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
Thanks, @waharnum!

**Comment by the-t-in-rtf** [comment]
@waharnum and @gtirloni, somehow Jenkins doesn't seem to have refreshed itself, I'm still seeing comments from the bot on open pulls and the jobs still exist. [See here for an example](https://github.com/fluid-project/fluid-grunt-lint-all/pull/12#issuecomment-654700746).

**Comment by gtirloni** [comment]
The update job failed to run: https://ci.gpii.net/view/All/job/update-jenkins-job-definitions/106/console

```
$ jenkins-jobs --conf /etc/jenkins_jobs.ini update --delete-old ./jenkins_jobs
INFO:root:Updating jobs in ['./jenkins_jobs'] ([])
Traceback (most recent call last):
  File "/bin/jenkins-jobs", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 191, in main
    execute(options, config)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 372, in execute
    n_workers=options.n_workers)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 348, in update_jobs
    self.load_files(input_fn)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 245, in load_files
    self.parser = YamlParser(self.global_config, self.plugins_list)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 241, in plugins_list
    self._plugins_list = self.jenkins.get_plugins_info()
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 205, in get_plugins_info
    raise e
jenkins.JenkinsException: Error in request. Possibly authentication failed [401]: Unauthorized
```

It seems the credentials in /etc/jenkins_job.ini (i-0011 server) could be incorrect.

I don't have access to GPII's Jenkins, maybe @amatas could take a look?

**Comment by amatas** [comment]
This PR is applied, sorry for being late, the notification of this thread was in a pile of another hundreds of similar mails.

**Comment by the-t-in-rtf** [comment]
Thanks, @amatas.

**Pull request merged**
